version: '3.8'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mystery
    expose:
      - 3306

  rabbitmq:
    restart: always
    image: "rabbitmq:3-management"
    environment:
      RABBITMQ_NODENAME: "rabbitmq@localhost"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    expose:
      - 5672
      - 15672

  setup:
    build: ./riddle_tree
    command: sh -c "celery -A riddle_tree beat  & celery -A riddle_tree worker"
    volumes:
      - ./riddle_tree:/project/mystery
    depends_on:
      - db
      - rabbitmq
    restart: on-failure

  consumer:
    build: ./riddle_tree
    command: sh -c "python consumer.py "
    volumes:
      - ./riddle_tree:/project/mystery
    depends_on:
      - db
      - rabbitmq
      - setup
    restart: on-failure

  mystery:
    build: ./riddle_tree
    command: sh -c "python manage.py migrate && gunicorn --bind 0.0.0.0:8000 riddle_tree.wsgi"
    volumes:
      - ./riddle_tree:/project/mystery
    ports:
      - "8000:8000"
    depends_on:
      - setup
    restart: always

  cashier:
    build: ./cashier
    command: 'python app.py'
    volumes:
      - ./cashier:/project/cashier
    ports:
      - "5000:5000"
    depends_on:
      - setup
    restart: always
