version: '3.8'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mystery
#    ports:
#      - "3306:3306"
    expose:
      - 3306

  rabbitmq:
    restart: always
    image: "rabbitmq:3-management"
    environment:
      RABBITMQ_NODENAME: "rabbitmq@localhost"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
#    ports:
#      - "15672:15672"
#      - "5672:5672"
    expose:
      - 5672
      - 15672
  setup:
    build: ./riddle_tree
    command: sh -c "python manage.py migrate & celery -A riddle_tree beat  & celery -A riddle_tree worker "
    depends_on:
      - db
      - rabbitmq

  mystery:
    build: ./riddle_tree
    command: sh -c " gunicorn --bind 0.0.0.0:8000 riddle_tree.wsgi"
    #    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./riddle_tree:/project/mystery
    ports:
      - "8000:8000"
    depends_on:
      - setup

  cashier:
    build: ./cashier
    command: 'python app.py'
    volumes:
      - ./cashier:/project/mystery
    ports:
      - "5000:5000"
    depends_on:
      - setup