version: '3.8'
### закомментированные строчки используются для сборки проекта
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mystery
    healthcheck:
        test: ['CMD', 'mysqladmin', '-uroot', '-proot', 'ping', '-h', 'db']
        interval: 30s
        timeout: 10s
        retries: 5
    expose:
      - 3306

  rabbitmq:
    restart: always
    image: "rabbitmq:3-management"
    environment:
      RABBITMQ_NODENAME: "rabbitmq@localhost"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    expose:
      - 5672
      - 15672

  mystery:
#    build: ./riddle_tree
    image: xinchaobojan/riddle_tree
    command: sh -c "python manage.py collectstatic --noinput && python manage.py migrate && celery -A riddle_tree beat  & celery -A riddle_tree worker & python consumer.py & gunicorn --bind 0.0.0.0:8000 riddle_tree.wsgi"
#    volumes:
#      - ./riddle_tree:/project/mystery
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

    restart: always

  cashier:
    image: xinchaobojan/cashier
#    build: ./cashier
    command: 'python app.py'
#    volumes:
#      - ./cashier:/project/cashier
    ports:
      - "5000:5000"
    depends_on:
      - db
      - rabbitmq

    restart: always
