# Generated by Django 4.0.2 on 2022-02-26 16:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswerinfo',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 26, 16, 49, 47, 223366, tzinfo=utc)),
        ),
    ]
