# Generated by Django 4.0.2 on 2022-02-27 09:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_useranswerinfo_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='text',
            field=models.TextField(default='jopa', verbose_name='Текст подсказки'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='useranswerinfo',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 27, 9, 46, 24, 129313, tzinfo=utc)),
        ),
    ]
