# Generated by Django 4.0.2 on 2022-02-27 11:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_prompt_text_alter_useranswerinfo_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='prompt', verbose_name='Файл с подсказкой'),
        ),
        migrations.AlterField(
            model_name='useranswerinfo',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 27, 11, 16, 21, 2934, tzinfo=utc)),
        ),
    ]
