# Generated by Django 4.0.2 on 2022-02-27 17:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_prompt_file_alter_useranswerinfo_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='finalist',
            field=models.BooleanField(default=False, verbose_name='Финалист'),
        ),
        migrations.AlterField(
            model_name='useranswerinfo',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 27, 17, 5, 32, 671764, tzinfo=utc)),
        ),
    ]
