# Generated by Django 4.0.2 on 2022-02-27 17:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_customuser_finalist_alter_useranswerinfo_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswerinfo',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
