# Generated by Django 4.0.2 on 2022-02-27 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_useranswerinfo_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='finalist',
            field=models.BooleanField(default=False, verbose_name='Финальный вопрос'),
        ),
    ]
