# Generated by Django 4.0.2 on 2022-02-27 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_answer_finalist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='finalist',
        ),
        migrations.AddField(
            model_name='question',
            name='final',
            field=models.BooleanField(default=False, verbose_name='Финальный вопрос'),
        ),
    ]
