# Generated by Django 4.0.2 on 2022-02-27 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_remove_answer_finalist_question_final'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='finalist',
        ),
        migrations.AddField(
            model_name='customuser',
            name='promocode',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Промокод'),
        ),
    ]
