# Generated by Django 4.0.2 on 2022-02-28 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_remove_customuser_finalist_customuser_promocode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='final',
        ),
        migrations.AddField(
            model_name='question',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Узел'), (2, 'Финальный'), (3, 'Тупик'), (4, 'Первый')], default=1, verbose_name='Статус вопроса'),
        ),
    ]
