# Generated by Django 3.2.12 on 2022-03-11 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_auto_20220311_1941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='promocode',
        ),
        migrations.AddField(
            model_name='promocode',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='promocode', to='main_app.customuser', verbose_name='Пользователь'),
            preserve_default=False,
        ),
    ]
