# Generated by Django 3.2.12 on 2022-03-11 20:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_auto_20220311_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='promocode', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
