# Generated by Django 3.2.12 on 2022-03-12 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_alter_promocode_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Активный'),
        ),
        migrations.AddField(
            model_name='promocode',
            name='qr',
            field=models.ImageField(blank=True, null=True, upload_to='qr', verbose_name='Qr код'),
        ),
        migrations.AddField(
            model_name='sale',
            name='slug',
            field=models.SlugField(default='50%', max_length=31, unique=True, verbose_name='Буквенный идентификатор'),
            preserve_default=False,
        ),
    ]
