# Generated by Django 3.2.12 on 2022-03-12 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_auto_20220312_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='slug',
            field=models.SlugField(default='12', max_length=31, unique=True, verbose_name='Буквенный идентификатор'),
            preserve_default=False,
        ),
    ]
